# Generated by Django 6.0.3 on 2026-03-19 14:20

import apps.activos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=80)),
                ('serie', models.CharField(db_index=True, max_length=120, unique=True)),
                ('cpu', models.CharField(blank=True, max_length=150)),
                ('ram', models.CharField(blank=True, max_length=50)),
                ('disco', models.CharField(blank=True, max_length=80)),
                ('sistema_operativo', models.CharField(default='Windows', max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado_activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='catalogos.estadoactivo')),
                ('tipo_activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='catalogos.tipoactivo')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='FotoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=apps.activos.models.ruta_foto_activo)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='activos.activo')),
            ],
            options={
                'verbose_name': 'Foto de activo',
                'verbose_name_plural': 'Fotos de activos',
                'ordering': ['activo', 'orden'],
                'constraints': [models.UniqueConstraint(fields=('activo', 'orden'), name='unique_orden_foto_por_activo')],
            },
        ),
    ]
