# Generated by Django 6.0.3 on 2026-03-19 18:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_alter_fotoactivo_orden'),
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateTimeField(default=django.utils.timezone.now)),
                ('detalle', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='activos.activo')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='catalogos.tipoeventoactivo')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_activo_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de activo',
                'verbose_name_plural': 'Eventos de activos',
                'ordering': ['-fecha_evento', '-id'],
            },
        ),
    ]
