# Generated by Django 6.0.3 on 2026-03-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0003_eventoactivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activo',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
