# Generated by Django 6.0.3 on 2026-04-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_activo_fecha_compra_activo_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='serie',
            field=models.CharField(blank=True, db_index=True, default='S/N', max_length=120),
        ),
    ]
