# Generated by Codex on 2026-04-27

from django.db import migrations, models


TIPOS_ACTIVO_CON_ESPECIFICACIONES = (
    "laptop",
    "pc",
    "desktop",
    "escritorio",
    "computador",
    "computadora",
)


def limpiar_especificaciones_no_aplicables(apps, schema_editor):
    Activo = apps.get_model("activos", "Activo")

    for activo in Activo.objects.select_related("tipo_activo").iterator():
        nombre_tipo = (activo.tipo_activo.nombre or "").strip().lower()
        requiere_especificaciones = any(
            clave in nombre_tipo for clave in TIPOS_ACTIVO_CON_ESPECIFICACIONES
        )

        if requiere_especificaciones:
            continue

        Activo.objects.filter(pk=activo.pk).update(
            cpu="",
            ram="",
            disco="",
            sistema_operativo="",
        )


class Migration(migrations.Migration):

    dependencies = [
        ("activos", "0005_alter_activo_serie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activo",
            name="sistema_operativo",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.RunPython(limpiar_especificaciones_no_aplicables, migrations.RunPython.noop),
    ]
