# Generated by Codex on 2026-04-27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0003_centrocosto"),
        ("activos", "0006_activo_sistema_operativo_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventoactivo",
            name="campo_afectado",
            field=models.CharField(
                choices=[
                    ("ninguno", "Ninguno"),
                    ("cpu", "Procesador"),
                    ("ram", "RAM"),
                    ("disco", "Disco"),
                    ("sistema_operativo", "Sistema operativo"),
                ],
                default="ninguno",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="eventoactivo",
            name="valor_anterior",
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name="eventoactivo",
            name="valor_nuevo",
            field=models.CharField(
                blank=True,
                help_text="Nuevo valor tecnico que se aplicara al activo, por ejemplo 16 GB.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="eventoactivo",
            name="costo_adicional",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Costo de repuesto o mejora. No aplica para mantenimiento simple.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eventoactivo",
            name="sumar_costo_al_valor",
            field=models.BooleanField(
                default=False,
                help_text="Suma el costo adicional al valor actual del activo.",
            ),
        ),
        migrations.AddField(
            model_name="eventoactivo",
            name="nuevo_estado_activo",
            field=models.ForeignKey(
                blank=True,
                help_text="Estado que tomara el activo despues del evento, si aplica.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="eventos_actualizacion",
                to="catalogos.estadoactivo",
            ),
        ),
    ]
