# Generated by Codex on 2026-04-27

import re
import unicodedata

from django.db import migrations


PREFIJOS_TIPOS_ACTIVO = {
    "laptop": "LAP",
    "mouse": "MOU",
    "mousepad": "MOUP",
    "teclado": "TEC",
    "base para laptop": "BLP",
    "pc": "PC",
}


def normalizar_nombre_tipo(nombre):
    nombre = unicodedata.normalize("NFKD", nombre or "")
    nombre = "".join(caracter for caracter in nombre if not unicodedata.combining(caracter))
    nombre = re.sub(r"[^a-zA-Z0-9]+", " ", nombre).strip().lower()
    return re.sub(r"\s+", " ", nombre)


def obtener_base_prefijo(nombre):
    nombre_normalizado = normalizar_nombre_tipo(nombre)
    return re.sub(r"[^A-Z0-9]+", "", nombre_normalizado.upper()) or "GEN"


def obtener_prefijo_tipo(nombre_tipo, codigos_usados, tipo_id, activos_por_tipo):
    nombre_normalizado = normalizar_nombre_tipo(nombre_tipo)
    if nombre_normalizado in PREFIJOS_TIPOS_ACTIVO:
        return PREFIJOS_TIPOS_ACTIVO[nombre_normalizado]

    base_prefijo = obtener_base_prefijo(nombre_tipo)
    longitud_inicial = min(3, len(base_prefijo))
    prefijos_reservados = {
        prefijo
        for tipo, prefijo in PREFIJOS_TIPOS_ACTIVO.items()
        if tipo != nombre_normalizado
    }
    prefijos_reservados.add("ACT")

    for longitud in range(longitud_inicial, len(base_prefijo) + 1):
        prefijo = base_prefijo[:longitud]
        if prefijo in prefijos_reservados:
            continue

        existe_en_otro_tipo = any(
            codigo.startswith(f"{prefijo}-")
            for otro_tipo_id, codigos in activos_por_tipo.items()
            if otro_tipo_id != tipo_id
            for codigo in codigos
        )
        if not existe_en_otro_tipo:
            return prefijo

    contador = 2
    prefijo_base = base_prefijo[:13]
    while True:
        prefijo = f"{prefijo_base}{contador}"
        existe_en_otro_tipo = any(
            codigo.startswith(f"{prefijo}-")
            for otro_tipo_id, codigos in activos_por_tipo.items()
            if otro_tipo_id != tipo_id
            for codigo in codigos
        )
        if prefijo not in prefijos_reservados and not existe_en_otro_tipo:
            return prefijo
        contador += 1


def siguiente_codigo(prefijo, codigos_usados):
    ultimo_numero = 0
    for codigo in codigos_usados:
        if not codigo.startswith(f"{prefijo}-"):
            continue
        try:
            ultimo_numero = max(ultimo_numero, int(codigo.split("-")[-1]))
        except (ValueError, IndexError):
            continue

    siguiente = ultimo_numero + 1
    while True:
        codigo = f"{prefijo}-{siguiente:04d}"
        if codigo not in codigos_usados:
            return codigo
        siguiente += 1


def normalizar_codigos_act(apps, schema_editor):
    Activo = apps.get_model("activos", "Activo")

    activos = list(Activo.objects.select_related("tipo_activo").order_by("id"))
    codigos_usados = {activo.codigo for activo in activos if activo.codigo}
    activos_por_tipo = {}
    for activo in activos:
        activos_por_tipo.setdefault(activo.tipo_activo_id, set()).add(activo.codigo)

    for activo in activos:
        if not (activo.codigo or "").upper().startswith("ACT-"):
            continue

        prefijo = obtener_prefijo_tipo(
            activo.tipo_activo.nombre,
            codigos_usados,
            activo.tipo_activo_id,
            activos_por_tipo,
        )
        nuevo_codigo = siguiente_codigo(prefijo, codigos_usados)

        codigos_usados.discard(activo.codigo)
        activos_por_tipo.get(activo.tipo_activo_id, set()).discard(activo.codigo)
        codigos_usados.add(nuevo_codigo)
        activos_por_tipo.setdefault(activo.tipo_activo_id, set()).add(nuevo_codigo)

        Activo.objects.filter(pk=activo.pk).update(codigo=nuevo_codigo)


class Migration(migrations.Migration):

    dependencies = [
        ("activos", "0007_eventoactivo_impacto"),
    ]

    operations = [
        migrations.RunPython(normalizar_codigos_act, migrations.RunPython.noop),
    ]
