# Generated by Django 6.0.3 on 2026-04-23 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_centrocosto'),
        ('colaboradores', '0002_colaborador_empresa_colaborador_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='centro_costo',
            field=models.ForeignKey(blank=True, help_text='CECO contable vigente del colaborador. Se copia a cada asignacion al crearla.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='catalogos.centrocosto'),
        ),
    ]
