# Generated by Django 6.0.3 on 2026-04-23 14:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_empresa_ubicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Codigo oficial del centro de costo segun ERP/Finanzas.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='El codigo CECO debe usar mayusculas, numeros, punto, guion o guion bajo.', regex='^[A-Z0-9][A-Z0-9._-]{1,29}$')])),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('ADMINISTRATIVO', 'Administrativo'), ('PROYECTO', 'Proyecto'), ('SERVICIO', 'Servicio compartido')], default='OPERATIVO', max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('acepta_asignaciones', models.BooleanField(default=True, help_text='Si esta desmarcado, no se permite copiar este CECO en nuevas asignaciones.')),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='centros_costo', to='catalogos.empresa')),
                ('padre', models.ForeignKey(blank=True, help_text='Permite modelar jerarquia tipo SAP: sociedad, division, area o subcentro.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcentros', to='catalogos.centrocosto')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='centros_costo_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Centro de costo',
                'verbose_name_plural': 'Centros de costo',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo', 'activo'], name='catalogos_c_codigo_2bfd59_idx'), models.Index(fields=['empresa', 'activo'], name='catalogos_c_empresa_5baba9_idx')],
            },
        ),
    ]
