# Generated by Django 6.0.3 on 2026-05-04 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0003_centrocosto"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartamentoEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("descripcion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departamentos",
                        to="catalogos.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Departamento de empresa",
                "verbose_name_plural": "Departamentos de empresa",
                "ordering": ["empresa__nombre", "nombre"],
            },
        ),
        migrations.AddConstraint(
            model_name="departamentoempresa",
            constraint=models.UniqueConstraint(
                fields=("empresa", "nombre"),
                name="unique_departamento_por_empresa",
            ),
        ),
        migrations.AddField(
            model_name="centrocosto",
            name="departamentos",
            field=models.ManyToManyField(
                blank=True,
                help_text="Departamentos de la empresa que engloba este CECO.",
                related_name="centros_costo",
                to="catalogos.departamentoempresa",
            ),
        ),
    ]
