# Generated by Django 6.0.3 on 2026-03-19 18:14

import apps.actas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to=apps.actas.models.ruta_acta_entrega)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255)),
                ('version_plantilla', models.CharField(default='1.0', max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Acta de entrega',
                'verbose_name_plural': 'Actas de entrega',
                'ordering': ['-fecha_generacion', '-id'],
            },
        ),
    ]
