# Generated by Django 6.0.3 on 2026-03-19 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actas', '0001_initial'),
        ('asignaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actaentrega',
            name='asignacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acta', to='asignaciones.asignacion'),
        ),
        migrations.AddField(
            model_name='actaentrega',
            name='usuario_generador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas_generadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
