# Generated by Django 6.0.3 on 2026-04-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaentrega',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='actaentrega',
            name='version_plantilla',
            field=models.CharField(default='2.0', max_length=20),
        ),
    ]
