# Generated by Codex on 2026-04-27

import apps.actas.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actas", "0003_actaentrega_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actaentrega",
            name="tipo",
            field=models.CharField(
                choices=[("ENTREGA", "Entrega"), ("RECEPCION", "Recepcion")],
                db_index=True,
                default="ENTREGA",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="actaentrega",
            name="archivo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.actas.models.ruta_acta_entrega,
            ),
        ),
        migrations.AlterField(
            model_name="actaentrega",
            name="asignacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actas",
                to="asignaciones.asignacion",
            ),
        ),
        migrations.AddConstraint(
            model_name="actaentrega",
            constraint=models.UniqueConstraint(
                fields=("asignacion", "tipo"),
                name="unique_acta_por_asignacion_tipo",
            ),
        ),
    ]
