# Generated by Django 6.0.3 on 2026-04-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0004_actaentrega_tipo_and_multiple_actas'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='actaentrega',
            name='unique_acta_por_asignacion_tipo',
        ),
    ]
