# Generated by Django 6.0.3 on 2026-04-27 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0005_remove_actaentrega_unique_acta_por_asignacion_tipo'),
        ('asignaciones', '0005_alter_asignacion_estado_asignacion_devolucion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actaentrega',
            name='devolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actas', to='asignaciones.devolucion'),
        ),
        migrations.AddConstraint(
            model_name='actaentrega',
            constraint=models.UniqueConstraint(condition=models.Q(('devolucion__isnull', True), ('tipo', 'ENTREGA')), fields=('asignacion', 'tipo'), name='unique_acta_entrega_por_asignacion'),
        ),
        migrations.AddConstraint(
            model_name='actaentrega',
            constraint=models.UniqueConstraint(condition=models.Q(('devolucion__isnull', False), ('tipo', 'RECEPCION')), fields=('devolucion', 'tipo'), name='unique_acta_recepcion_por_devolucion'),
        ),
    ]
