# Generated by Django 6.0.3 on 2026-03-19 18:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0003_eventoactivo'),
        ('catalogos', '0001_initial'),
        ('colaboradores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(default=django.utils.timezone.now)),
                ('observaciones_entrega', models.TextField(blank=True)),
                ('estado_asignacion', models.CharField(choices=[('ACTIVA', 'Activa'), ('CERRADA', 'Cerrada')], default='ACTIVA', max_length=10)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('observaciones_devolucion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='activos.activo')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='colaboradores.colaborador')),
                ('estado_activo_devolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_cerradas', to='catalogos.estadoactivo')),
                ('usuario_recepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_registradas', to=settings.AUTH_USER_MODEL)),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'ordering': ['-fecha_asignacion', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado_asignacion', 'ACTIVA')), fields=('activo',), name='unique_asignacion_activa_por_activo')],
            },
        ),
    ]
