# Generated by Django 6.0.3 on 2026-03-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='codigo_asignacion',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
