# Generated by Django 6.0.3 on 2026-04-10 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_activo_fecha_compra_activo_valor'),
        ('asignaciones', '0002_asignacion_codigo_asignacion'),
        ('catalogos', '0002_empresa_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('observaciones_linea', models.TextField(blank=True)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('observaciones_devolucion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Detalle de asignación',
                'verbose_name_plural': 'Detalles de asignación',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='asignacion',
            name='unique_asignacion_activa_por_activo',
        ),
        migrations.AddField(
            model_name='asignaciondetalle',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_asignacion', to='activos.activo'),
        ),
        migrations.AddField(
            model_name='asignaciondetalle',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='asignaciones.asignacion'),
        ),
        migrations.AddField(
            model_name='asignaciondetalle',
            name='estado_activo_devolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_asignacion_cerrados', to='catalogos.estadoactivo'),
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='estado_activo_devolucion',
        ),
        migrations.AddConstraint(
            model_name='asignaciondetalle',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('activo',), name='unique_detalle_asignacion_activa_por_activo'),
        ),
        migrations.AddConstraint(
            model_name='asignaciondetalle',
            constraint=models.UniqueConstraint(fields=('asignacion', 'activo'), name='unique_activo_por_asignacion'),
        ),
    ]
