# Generated by Django 6.0.3 on 2026-04-23 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0003_asignaciondetalle_and_more'),
        ('catalogos', '0003_centrocosto'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='centro_costo',
            field=models.ForeignKey(blank=True, editable=False, help_text='CECO historico copiado desde el colaborador al crear la asignacion.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='catalogos.centrocosto'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='centro_costo_codigo',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='centro_costo_empresa',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='centro_costo_nombre',
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
    ]
