# Generated by Django 6.0.3 on 2026-04-27 17:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0004_asignacion_centro_costo_and_more'),
        ('catalogos', '0003_centrocosto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='estado_asignacion',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('PARCIAL', 'Parcial'), ('CERRADA', 'Cerrada')], default='ACTIVA', max_length=10),
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_devolucion', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('fecha_devolucion', models.DateField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='asignaciones.asignacion')),
                ('usuario_recepcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_devolucion_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devolucion',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-fecha_devolucion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DevolucionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detalle_asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='asignaciones.asignaciondetalle')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='asignaciones.devolucion')),
                ('estado_activo_devolucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_devolucion', to='catalogos.estadoactivo')),
            ],
            options={
                'verbose_name': 'Detalle de devolucion',
                'verbose_name_plural': 'Detalles de devolucion',
                'ordering': ['detalle_asignacion__orden', 'id'],
                'constraints': [models.UniqueConstraint(fields=('detalle_asignacion',), name='unique_devolucion_por_detalle_asignacion'), models.UniqueConstraint(fields=('devolucion', 'detalle_asignacion'), name='unique_detalle_por_devolucion')],
            },
        ),
    ]
