# Generated by Codex on 2026-04-27

from django.db import migrations


def normalizar_codigos_devolucion(apps, schema_editor):
    Devolucion = apps.get_model("asignaciones", "Devolucion")
    for devolucion in Devolucion.objects.order_by("id"):
        codigo = f"DEV-{devolucion.pk:05d}"
        if devolucion.codigo_devolucion != codigo:
            devolucion.codigo_devolucion = codigo
            devolucion.save(update_fields=["codigo_devolucion"])


class Migration(migrations.Migration):

    dependencies = [
        ("asignaciones", "0005_alter_asignacion_estado_asignacion_devolucion_and_more"),
    ]

    operations = [
        migrations.RunPython(normalizar_codigos_devolucion, migrations.RunPython.noop),
    ]
